//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FMS_DevelopEntities : DbContext
    {
        public FMS_DevelopEntities()
            : base("name=FMS_DevelopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<R_CompanyAccount> R_CompanyAccount { get; set; }
        public DbSet<R_CompanyCurrceny> R_CompanyCurrceny { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T_Assets> T_Assets { get; set; }
        public DbSet<T_AssetsGroup> T_AssetsGroup { get; set; }
        public DbSet<T_Bank> T_Bank { get; set; }
        public DbSet<T_BeginningBalance> T_BeginningBalance { get; set; }
        public DbSet<T_BusinessCost> T_BusinessCost { get; set; }
        public DbSet<T_BusinessPartner> T_BusinessPartner { get; set; }
        public DbSet<T_CashFlowItem> T_CashFlowItem { get; set; }
        public DbSet<T_Company> T_Company { get; set; }
        public DbSet<T_CompanySetting> T_CompanySetting { get; set; }
        public DbSet<T_CurrencyCode> T_CurrencyCode { get; set; }
        public DbSet<T_DeclareCostSpending> T_DeclareCostSpending { get; set; }
        public DbSet<T_DeclareCustomer> T_DeclareCustomer { get; set; }
        public DbSet<T_DetailedAccount> T_DetailedAccount { get; set; }
        public DbSet<T_DetailedCategories> T_DetailedCategories { get; set; }
        public DbSet<T_ExpenseType> T_ExpenseType { get; set; }
        public DbSet<T_GeneralLedgerAccount> T_GeneralLedgerAccount { get; set; }
        public DbSet<T_IEDetails> T_IEDetails { get; set; }
        public DbSet<T_IEHistoryDetails> T_IEHistoryDetails { get; set; }
        public DbSet<T_IEHistoryRecord> T_IEHistoryRecord { get; set; }
        public DbSet<T_IEWriteOff> T_IEWriteOff { get; set; }
        public DbSet<T_InvType> T_InvType { get; set; }
        public DbSet<T_ModuleList> T_ModuleList { get; set; }
        public DbSet<T_Payable> T_Payable { get; set; }
        public DbSet<T_RateHistory> T_RateHistory { get; set; }
        public DbSet<T_Receivables> T_Receivables { get; set; }
        public DbSet<T_RecPayHistoryRecord> T_RecPayHistoryRecord { get; set; }
        public DbSet<T_RecPayRecord> T_RecPayRecord { get; set; }
        public DbSet<T_Report> T_Report { get; set; }
        public DbSet<T_Tax> T_Tax { get; set; }
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_WageCost> T_WageCost { get; set; }
        public DbSet<V_CompanyAccounts> V_CompanyAccounts { get; set; }
        public DbSet<V_IEDetails> V_IEDetails { get; set; }
        public DbSet<V_IERecord> V_IERecord { get; set; }
        public DbSet<V_IERecords> V_IERecords { get; set; }
        public DbSet<V_Payable> V_Payable { get; set; }
        public DbSet<V_Receivable> V_Receivable { get; set; }
        public DbSet<V_RerPayRecord> V_RerPayRecord { get; set; }
        public DbSet<T_AssetCostType> T_AssetCostType { get; set; }
        public DbSet<T_Product_Saled> T_Product_Saled { get; set; }
        public DbSet<T_AID_Product> T_AID_Product { get; set; }
        public DbSet<V_Product_Saled_Detail> V_Product_Saled_Detail { get; set; }
        public DbSet<T_ReportDetails> T_ReportDetails { get; set; }
        public DbSet<V_Prodcut_List> V_Prodcut_List { get; set; }
        public DbSet<T_AIDSubTypeRecord> T_AIDSubTypeRecord { get; set; }
        public DbSet<T_AIDTypeRecord> T_AIDTypeRecord { get; set; }
        public DbSet<T_Product> T_Product { get; set; }
        public DbSet<T_AIDRecord> T_AIDRecord { get; set; }
        public DbSet<T_IERecord> T_IERecord { get; set; }
    
        public virtual ObjectResult<SP_QueryIEListForProductSales_Result> SP_QueryIEListForProductSales(string c_guid)
        {
            var c_guidParameter = c_guid != null ?
                new ObjectParameter("c_guid", c_guid) :
                new ObjectParameter("c_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_QueryIEListForProductSales_Result>("SP_QueryIEListForProductSales", c_guidParameter);
        }
    }
}
