//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AID_Product
    {
        public string GUID { get; set; }
        public string AID_Guid { get; set; }
        public Nullable<decimal> Use_AID_Amount { get; set; }
        public string Product_Guid { get; set; }
    }
}
