//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AIDSubTypeRecord
    {
        public string AST_GUID { get; set; }
        public string ASTTypeName { get; set; }
        public string AST_ParentAidType { get; set; }
        public string Remark { get; set; }
        public string Depreciation_year { get; set; }
    }
}
