//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BusinessPartner
    {
        public string BP_GUID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsPartner { get; set; }
        public string C_GUID { get; set; }
        public string ChineseFullName { get; set; }
        public string EnglishFullName { get; set; }
        public string Website { get; set; }
        public string OrganizationCode { get; set; }
        public string IndustryInvolved { get; set; }
        public string RegisteredAddress { get; set; }
        public string Remark { get; set; }
    }
}
