//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Company
    {
        public string C_GUID { get; set; }
        public string MasterCompanyGuid { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contacter { get; set; }
        public string ContactWay { get; set; }
        public string Type { get; set; }
        public string AuditDate { get; set; }
        public string ChineseFullName { get; set; }
        public string EnglishFullName { get; set; }
        public string Website { get; set; }
        public string OrganizationCode { get; set; }
        public string IndustryInvolved { get; set; }
        public string RegisteredAddress { get; set; }
        public string Remark { get; set; }
        public string LOGO { get; set; }
        public string BusinessLicense { get; set; }
        public string CompanyID { get; set; }
        public string Taxpayer { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
    }
}
