//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IERecord
    {
        public string IE_GUID { get; set; }
        public string IE_Flag { get; set; }
        public string InvType { get; set; }
        public string InvNo { get; set; }
        public string RPer { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string C_GUID { get; set; }
        public Nullable<System.DateTime> AffirmDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxationAmount { get; set; }
        public string TaxationType { get; set; }
        public Nullable<decimal> SumAmount { get; set; }
        public string Remark { get; set; }
        public string Currency { get; set; }
        public string B_GUID { get; set; }
        public string BA_GUID { get; set; }
        public string IEGroup { get; set; }
        public string IEDescription { get; set; }
        public string RP_GUID { get; set; }
        public string State { get; set; }
        public string Profit_GUID { get; set; }
        public string Material_type { get; set; }
        public string GUID_Parent { get; set; }
        public Nullable<decimal> Resale_Amount { get; set; }
        public string Business_GUID { get; set; }
        public string SubBusiness_GUID { get; set; }
        public Nullable<decimal> TaxdomesticAmount { get; set; }
        public Nullable<decimal> DomesticAmount { get; set; }
        public Nullable<decimal> DomesticSumAmount { get; set; }
    }
}
