//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Report
    {
        public string Rep_GUID { get; set; }
        public string RepNo { get; set; }
        public string Type { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string C_GUID { get; set; }
        public string period_type { get; set; }
        public string rep_date { get; set; }
        public string rep_status { get; set; }
    }
}
