//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Receivables
    {
        public string R_GUID { get; set; }
        public string C_GUID { get; set; }
        public string Payer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InvType { get; set; }
        public string InvNo { get; set; }
        public string B_GUID { get; set; }
        public string BA_GUID { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string Currency { get; set; }
    }
}
