//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReportDetails
    {
        public string GUID { get; set; }
        public string rep_guid { get; set; }
        public string row_no { get; set; }
        public string name { get; set; }
        public Nullable<decimal> beginning_amount { get; set; }
        public Nullable<decimal> ending_amount { get; set; }
    }
}
