//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public string U_GUID { get; set; }
        public string C_GUID { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> State { get; set; }
        public string EnterC_GUID { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string GroupCode { get; set; }
        public string Language { get; set; }
        public string TelName { get; set; }
        public string SuperUser { get; set; }
    }
}
