//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Product_Saled_Detail
    {
        public string id { get; set; }
        public string sale_batch_id { get; set; }
        public string product_guid { get; set; }
        public string ie_guid { get; set; }
        public string saled_date { get; set; }
        public string customer_name { get; set; }
        public string C_GUID { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> saled_amount { get; set; }
        public Nullable<decimal> SumAmount { get; set; }
    }
}
