//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BalanceSheetTemplate
    {
        public int id { get; set; }
        public string asset_item_name { get; set; }
        public Nullable<int> asset_row_no { get; set; }
        public Nullable<decimal> asset_start_amount { get; set; }
        public Nullable<decimal> asset_end_amount { get; set; }
        public string debt_item_name { get; set; }
        public Nullable<int> debt_row_no { get; set; }
        public Nullable<decimal> debt_start_amount { get; set; }
        public Nullable<decimal> debt_end_amount { get; set; }
        public string rep_status { get; set; }
        
    }
}
