//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public class T_CashFlowItemTemplate 
    {
        public int id { get; set; }
        public string name { get; set; }
        public string row_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string additional { get; set; }
        public string row_no_add { get; set; }
        public Nullable<decimal> amount_add { get; set; }
    }
}
