//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IncomeStatementTemplate
    {
        public int id { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> amount_p { get; set; }
        public Nullable<decimal> amount_r { get; set; }
        public string item_name { get; set; }
        public Nullable<int> row_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> amount_sum { get; set; }
    }
}
