//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Resource.FinanceReport {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinanceReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinanceReport() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMS.Resource.FinanceReport.FinanceReport", typeof(FinanceReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 科目 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资产合计: 的本地化字符串。
        /// </summary>
        public static string AssetSum {
            get {
                return ResourceManager.GetString("AssetSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资产负债表 的本地化字符串。
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到期初数，请先设置期初数 的本地化字符串。
        /// </summary>
        public static string BeginningBalanceError {
            get {
                return ResourceManager.GetString("BeginningBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置期初数 的本地化字符串。
        /// </summary>
        public static string BeginningBalanceSetting {
            get {
                return ResourceManager.GetString("BeginningBalanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期初数 的本地化字符串。
        /// </summary>
        public static string BeginningValue {
            get {
                return ResourceManager.GetString("BeginningValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期末数 的本地化字符串。
        /// </summary>
        public static string EndingValue {
            get {
                return ResourceManager.GetString("EndingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利润表 的本地化字符串。
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负债及所有者权益合计: 的本地化字符串。
        /// </summary>
        public static string LiabilitySum {
            get {
                return ResourceManager.GetString("LiabilitySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表时间 的本地化字符串。
        /// </summary>
        public static string RepDate {
            get {
                return ResourceManager.GetString("RepDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表编号 的本地化字符串。
        /// </summary>
        public static string RepNo {
            get {
                return ResourceManager.GetString("RepNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验失败 的本地化字符串。
        /// </summary>
        public static string VaildError {
            get {
                return ResourceManager.GetString("VaildError", resourceCulture);
            }
        }
    }
}
