//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Resource.Currency {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Currency {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currency() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMS.Resource.Currency.Currency", typeof(Currency).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 阿联酋迪拉姆 的本地化字符串。
        /// </summary>
        public static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿富汗尼 的本地化字符串。
        /// </summary>
        public static string AFA {
            get {
                return ResourceManager.GetString("AFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿尔巴尼亚 的本地化字符串。
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亚美尼亚 的本地化字符串。
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安第列斯群岛盾 的本地化字符串。
        /// </summary>
        public static string ANG {
            get {
                return ResourceManager.GetString("ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安哥拉 的本地化字符串。
        /// </summary>
        public static string AON {
            get {
                return ResourceManager.GetString("AON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿根廷比索 的本地化字符串。
        /// </summary>
        public static string ARP {
            get {
                return ResourceManager.GetString("ARP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奥地利先令 的本地化字符串。
        /// </summary>
        public static string ATS {
            get {
                return ResourceManager.GetString("ATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澳大利亚元 的本地化字符串。
        /// </summary>
        public static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿鲁巴岛弗罗林 的本地化字符串。
        /// </summary>
        public static string AWF {
            get {
                return ResourceManager.GetString("AWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿塞拜疆 的本地化字符串。
        /// </summary>
        public static string AZM {
            get {
                return ResourceManager.GetString("AZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波斯尼亚和黑塞哥维那 的本地化字符串。
        /// </summary>
        public static string BAK {
            get {
                return ResourceManager.GetString("BAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巴巴多斯元 的本地化字符串。
        /// </summary>
        public static string BBD {
            get {
                return ResourceManager.GetString("BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BEF 的本地化字符串。
        /// </summary>
        public static string BEF {
            get {
                return ResourceManager.GetString("BEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿尔及利亚第纳尔 的本地化字符串。
        /// </summary>
        public static string DZD {
            get {
                return ResourceManager.GetString("DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安道尔法郎 的本地化字符串。
        /// </summary>
        public static string FRF {
            get {
                return ResourceManager.GetString("FRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安提瓜和巴布达岛东加勒比海元 的本地化字符串。
        /// </summary>
        public static string XCD {
            get {
                return ResourceManager.GetString("XCD", resourceCulture);
            }
        }
    }
}
