//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Resource.Finance {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Finance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Finance() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMS.Resource.Finance.Finance", typeof(Finance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认日期 的本地化字符串。
        /// </summary>
        public static string AffirmDate {
            get {
                return ResourceManager.GetString("AffirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账期截止日期 的本地化字符串。
        /// </summary>
        public static string ClosingDate {
            get {
                return ResourceManager.GetString("ClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本 的本地化字符串。
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贷方明细科目 的本地化字符串。
        /// </summary>
        public static string CreditDetailsAccount {
            get {
                return ResourceManager.GetString("CreditDetailsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贷方总账科目 的本地化字符串。
        /// </summary>
        public static string CreditLedgerAccount {
            get {
                return ResourceManager.GetString("CreditLedgerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币 的本地化字符串。
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期输入错误 的本地化字符串。
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借方明细科目 的本地化字符串。
        /// </summary>
        public static string DebitDetailsAccount {
            get {
                return ResourceManager.GetString("DebitDetailsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借方总账科目 的本地化字符串。
        /// </summary>
        public static string DebitLedgerAccount {
            get {
                return ResourceManager.GetString("DebitLedgerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用 的本地化字符串。
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用描述 的本地化字符串。
        /// </summary>
        public static string ExpenseDescription {
            get {
                return ResourceManager.GetString("ExpenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止日期 的本地化字符串。
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Explicit {
            get {
                return ResourceManager.GetString("Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票/凭证号 的本地化字符串。
        /// </summary>
        public static string InvNo {
            get {
                return ResourceManager.GetString("InvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本凭证单据号 的本地化字符串。
        /// </summary>
        public static string InvNoCost {
            get {
                return ResourceManager.GetString("InvNoCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据类型 的本地化字符串。
        /// </summary>
        public static string InvType {
            get {
                return ResourceManager.GetString("InvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应付账款记录 的本地化字符串。
        /// </summary>
        public static string PayablesRecordList {
            get {
                return ResourceManager.GetString("PayablesRecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款账户 的本地化字符串。
        /// </summary>
        public static string PayAccount {
            get {
                return ResourceManager.GetString("PayAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收款方 的本地化字符串。
        /// </summary>
        public static string Payee {
            get {
                return ResourceManager.GetString("Payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款方 的本地化字符串。
        /// </summary>
        public static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款 的本地化字符串。
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款账户 的本地化字符串。
        /// </summary>
        public static string PaymentAccount {
            get {
                return ResourceManager.GetString("PaymentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收入 的本地化字符串。
        /// </summary>
        public static string Proceeds {
            get {
                return ResourceManager.GetString("Proceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收款账户 的本地化字符串。
        /// </summary>
        public static string ReceivableAccount {
            get {
                return ResourceManager.GetString("ReceivableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应收账款记录 的本地化字符串。
        /// </summary>
        public static string ReceivablesRecordList {
            get {
                return ResourceManager.GetString("ReceivablesRecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收款 的本地化字符串。
        /// </summary>
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 科目 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总金额 的本地化字符串。
        /// </summary>
        public static string SumAmount {
            get {
                return ResourceManager.GetString("SumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 税金 的本地化字符串。
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 税费 的本地化字符串。
        /// </summary>
        public static string Taxation {
            get {
                return ResourceManager.GetString("Taxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 税种 的本地化字符串。
        /// </summary>
        public static string TaxationType {
            get {
                return ResourceManager.GetString("TaxationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销账记录 的本地化字符串。
        /// </summary>
        public static string WriteOffList {
            get {
                return ResourceManager.GetString("WriteOffList", resourceCulture);
            }
        }
    }
}
