//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Resource.FixedAssets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixedAssets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedAssets() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMS.Resource.FixedAssets.FixedAssets", typeof(FixedAssets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 固定资产原值 的本地化字符串。
        /// </summary>
        public static string AssetsCost {
            get {
                return ResourceManager.GetString("AssetsCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资产分类 的本地化字符串。
        /// </summary>
        public static string AssetsGroup {
            get {
                return ResourceManager.GetString("AssetsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认报废此资产？ 的本地化字符串。
        /// </summary>
        public static string ConfirmScrap {
            get {
                return ResourceManager.GetString("ConfirmScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认出售此资产？ 的本地化字符串。
        /// </summary>
        public static string ConfirmSell {
            get {
                return ResourceManager.GetString("ConfirmSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前资产值 的本地化字符串。
        /// </summary>
        public static string CurrCost {
            get {
                return ResourceManager.GetString("CurrCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余价值 的本地化字符串。
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折旧方法 的本地化字符串。
        /// </summary>
        public static string DepreciationMethod {
            get {
                return ResourceManager.GetString("DepreciationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在库 的本地化字符串。
        /// </summary>
        public static string InTheLibrary {
            get {
                return ResourceManager.GetString("InTheLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 借出 的本地化字符串。
        /// </summary>
        public static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用寿命(年) 的本地化字符串。
        /// </summary>
        public static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资产编号 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人 的本地化字符串。
        /// </summary>
        public static string PersonInCharge {
            get {
                return ResourceManager.GetString("PersonInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购置日期 的本地化字符串。
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人 的本地化字符串。
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册资产 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退还 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 残值率(%) 的本地化字符串。
        /// </summary>
        public static string SalvageRate {
            get {
                return ResourceManager.GetString("SalvageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定资产净残值 的本地化字符串。
        /// </summary>
        public static string SalvageValue {
            get {
                return ResourceManager.GetString("SalvageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废 的本地化字符串。
        /// </summary>
        public static string Scrap {
            get {
                return ResourceManager.GetString("Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废日期 的本地化字符串。
        /// </summary>
        public static string ScrapDate {
            get {
                return ResourceManager.GetString("ScrapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销类型 的本地化字符串。
        /// </summary>
        public static string ScrapType {
            get {
                return ResourceManager.GetString("ScrapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出售 的本地化字符串。
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Stat {
            get {
                return ResourceManager.GetString("Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用中 的本地化字符串。
        /// </summary>
        public static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
    }
}
