//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Resource.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝访问.
        /// </summary>
        public static string Access_Denied {
            get {
                return ResourceManager.GetString("Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问超时.
        /// </summary>
        public static string AccessTimeout {
            get {
                return ResourceManager.GetString("AccessTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号或密码错误.
        /// </summary>
        public static string AccOrPwdWrong {
            get {
                return ResourceManager.GetString("AccOrPwdWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同意.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审批.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核时间.
        /// </summary>
        public static string AuditDate {
            get {
                return ResourceManager.GetString("AuditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核人.
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后退.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请修改密码.
        /// </summary>
        public static string ChangePwd {
            get {
                return ResourceManager.GetString("ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请检查工号设置！.
        /// </summary>
        public static string CheckNumSetting {
            get {
                return ResourceManager.GetString("CheckNumSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查设置.
        /// </summary>
        public static string CheckSetting {
            get {
                return ResourceManager.GetString("CheckSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司ID.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司名称.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建日期.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据不能为空.
        /// </summary>
        public static string DataNotEmpty {
            get {
                return ResourceManager.GetString("DataNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上级部门不能选中本身.
        /// </summary>
        public static string DepNotChooseSelf {
            get {
                return ResourceManager.GetString("DepNotChooseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明细.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱格式不正确.
        /// </summary>
        public static string ErrorEmailType {
            get {
                return ResourceManager.GetString("ErrorEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已存在.
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此编号已存在.
        /// </summary>
        public static string ExistNumber {
            get {
                return ResourceManager.GetString("ExistNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在待处理请求.
        /// </summary>
        public static string ExistPending {
            get {
                return ResourceManager.GetString("ExistPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在未处理申请.
        /// </summary>
        public static string ExistPendingApproval {
            get {
                return ResourceManager.GetString("ExistPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败！.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件大小不能超出25M.
        /// </summary>
        public static string File_size_can_not_exceed_25M {
            get {
                return ResourceManager.GetString("File_size_can_not_exceed_25M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件重复.
        /// </summary>
        public static string FilterRepeat {
            get {
                return ResourceManager.GetString("FilterRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该职位未设置权限.
        /// </summary>
        public static string LackOfCompetence {
            get {
                return ResourceManager.GetString("LackOfCompetence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尾页.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从其他机构导入.
        /// </summary>
        public static string Lead_In {
            get {
                return ResourceManager.GetString("Lead_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string ListNo {
            get {
                return ResourceManager.GetString("ListNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入超时,请重新登入.
        /// </summary>
        public static string Login_in_Time_Out {
            get {
                return ResourceManager.GetString("Login_in_Time_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看权限.
        /// </summary>
        public static string LookUpAuthority {
            get {
                return ResourceManager.GetString("LookUpAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此功能需在不同站点间使用.
        /// </summary>
        public static string MustDifferent {
            get {
                return ResourceManager.GetString("MustDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该输入项为必输项.
        /// </summary>
        public static string MustEnter {
            get {
                return ResourceManager.GetString("MustEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无权限访问!.
        /// </summary>
        public static string No_permission_to_access {
            get {
                return ResourceManager.GetString("No_permission_to_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此工号非管理员.
        /// </summary>
        public static string NoAdmin {
            get {
                return ResourceManager.GetString("NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统无响应.
        /// </summary>
        public static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无此管理员.
        /// </summary>
        public static string NotFoundTheAdmin {
            get {
                return ResourceManager.GetString("NotFoundTheAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到相应信息！.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无处理项.
        /// </summary>
        public static string Null_Deal {
            get {
                return ResourceManager.GetString("Null_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归档.
        /// </summary>
        public static string Pigeonhole {
            get {
                return ResourceManager.GetString("Pigeonhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重新登录.
        /// </summary>
        public static string ReLogin {
            get {
                return ResourceManager.GetString("ReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string RemberPwd {
            get {
                return ResourceManager.GetString("RemberPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必填.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重设密码.
        /// </summary>
        public static string ResetPwd {
            get {
                return ResourceManager.GetString("ResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退回.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 终止.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功！.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超出系统使用期限！.
        /// </summary>
        public static string SystemTimeOut {
            get {
                return ResourceManager.GetString("SystemTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可用.
        /// </summary>
        public static string Unused {
            get {
                return ResourceManager.GetString("Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日期.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新人.
        /// </summary>
        public static string Updater {
            get {
                return ResourceManager.GetString("Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此用户已登录！.
        /// </summary>
        public static string UserLogined {
            get {
                return ResourceManager.GetString("UserLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验码已过期.
        /// </summary>
        public static string VerifyCodeOverdue {
            get {
                return ResourceManager.GetString("VerifyCodeOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验码不正确.
        /// </summary>
        public static string VerifyCodeWrong {
            get {
                return ResourceManager.GetString("VerifyCodeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎登入.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 销账.
        /// </summary>
        public static string WriteOff {
            get {
                return ResourceManager.GetString("WriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
