//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace General.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Resource.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝访问 的本地化字符串。
        /// </summary>
        public static string Access_Denied {
            get {
                return ResourceManager.GetString("Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问超时 的本地化字符串。
        /// </summary>
        public static string AccessTimeout {
            get {
                return ResourceManager.GetString("AccessTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或密码错误 的本地化字符串。
        /// </summary>
        public static string AccOrPwdWrong {
            get {
                return ResourceManager.GetString("AccOrPwdWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批 的本地化字符串。
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核时间 的本地化字符串。
        /// </summary>
        public static string AuditDate {
            get {
                return ResourceManager.GetString("AuditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核人 的本地化字符串。
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请修改密码 的本地化字符串。
        /// </summary>
        public static string ChangePwd {
            get {
                return ResourceManager.GetString("ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败，请检查工号设置！ 的本地化字符串。
        /// </summary>
        public static string CheckNumSetting {
            get {
                return ResourceManager.GetString("CheckNumSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查设置 的本地化字符串。
        /// </summary>
        public static string CheckSetting {
            get {
                return ResourceManager.GetString("CheckSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除? 的本地化字符串。
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不能为空 的本地化字符串。
        /// </summary>
        public static string DataNotEmpty {
            get {
                return ResourceManager.GetString("DataNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级部门不能选中本身 的本地化字符串。
        /// </summary>
        public static string DepNotChooseSelf {
            get {
                return ResourceManager.GetString("DepNotChooseSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入 的本地化字符串。
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱格式不正确 的本地化字符串。
        /// </summary>
        public static string ErrorEmailType {
            get {
                return ResourceManager.GetString("ErrorEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在 的本地化字符串。
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此编号已存在 的本地化字符串。
        /// </summary>
        public static string ExistNumber {
            get {
                return ResourceManager.GetString("ExistNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在待处理请求 的本地化字符串。
        /// </summary>
        public static string ExistPending {
            get {
                return ResourceManager.GetString("ExistPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在未处理申请 的本地化字符串。
        /// </summary>
        public static string ExistPendingApproval {
            get {
                return ResourceManager.GetString("ExistPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小不能超出25M 的本地化字符串。
        /// </summary>
        public static string File_size_can_not_exceed_25M {
            get {
                return ResourceManager.GetString("File_size_can_not_exceed_25M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件重复 的本地化字符串。
        /// </summary>
        public static string FilterRepeat {
            get {
                return ResourceManager.GetString("FilterRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该职位未设置权限 的本地化字符串。
        /// </summary>
        public static string LackOfCompetence {
            get {
                return ResourceManager.GetString("LackOfCompetence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从其他机构导入 的本地化字符串。
        /// </summary>
        public static string Lead_In {
            get {
                return ResourceManager.GetString("Lead_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string ListNo {
            get {
                return ResourceManager.GetString("ListNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入超时,请重新登入 的本地化字符串。
        /// </summary>
        public static string Login_in_Time_Out {
            get {
                return ResourceManager.GetString("Login_in_Time_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看权限 的本地化字符串。
        /// </summary>
        public static string LookUpAuthority {
            get {
                return ResourceManager.GetString("LookUpAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此功能需在不同站点间使用 的本地化字符串。
        /// </summary>
        public static string MustDifferent {
            get {
                return ResourceManager.GetString("MustDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项为必输项 的本地化字符串。
        /// </summary>
        public static string MustEnter {
            get {
                return ResourceManager.GetString("MustEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权限访问! 的本地化字符串。
        /// </summary>
        public static string No_permission_to_access {
            get {
                return ResourceManager.GetString("No_permission_to_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此工号非管理员 的本地化字符串。
        /// </summary>
        public static string NoAdmin {
            get {
                return ResourceManager.GetString("NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统无响应 的本地化字符串。
        /// </summary>
        public static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是 的本地化字符串。
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无此管理员 的本地化字符串。
        /// </summary>
        public static string NotFoundTheAdmin {
            get {
                return ResourceManager.GetString("NotFoundTheAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到相应信息！ 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无处理项 的本地化字符串。
        /// </summary>
        public static string Null_Deal {
            get {
                return ResourceManager.GetString("Null_Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人 的本地化字符串。
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归档 的本地化字符串。
        /// </summary>
        public static string Pigeonhole {
            get {
                return ResourceManager.GetString("Pigeonhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新登录 的本地化字符串。
        /// </summary>
        public static string ReLogin {
            get {
                return ResourceManager.GetString("ReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string RemberPwd {
            get {
                return ResourceManager.GetString("RemberPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重设密码 的本地化字符串。
        /// </summary>
        public static string ResetPwd {
            get {
                return ResourceManager.GetString("ResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出系统使用期限！ 的本地化字符串。
        /// </summary>
        public static string SystemTimeOut {
            get {
                return ResourceManager.GetString("SystemTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可用 的本地化字符串。
        /// </summary>
        public static string Unused {
            get {
                return ResourceManager.GetString("Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新日期 的本地化字符串。
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新人 的本地化字符串。
        /// </summary>
        public static string Updater {
            get {
                return ResourceManager.GetString("Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用 的本地化字符串。
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户已登录！ 的本地化字符串。
        /// </summary>
        public static string UserLogined {
            get {
                return ResourceManager.GetString("UserLogined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验码不正确 的本地化字符串。
        /// </summary>
        public static string VerifyCodeWrong {
            get {
                return ResourceManager.GetString("VerifyCodeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登入 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销账 的本地化字符串。
        /// </summary>
        public static string WriteOff {
            get {
                return ResourceManager.GetString("WriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
